SVY-19808 Search in date fields doesn't work for listForm component
you can't set a value to null like viewDate because the lib doesn't
support this when doing a deep copy of the options:

TypeError: Cannot convert undefined or null to object
    at Object.keys (<anonymous>)
    at _OptionConverter.deepCopy
(http://localhost:8183/chunk-3LFKNP7Q.js:45107:12)
    at http://localhost:8183/chunk-3LFKNP7Q.js:45119:35
    at Array.forEach (<anonymous>)
    at _OptionConverter.deepCopy
(http://localhost:8183/chunk-3LFKNP7Q.js:45107:24)
    at TempusDominus._initializeOptions
(http://localhost:8183/chunk-3LFKNP7Q.js:47418:37)
    at new TempusDominus
(http://localhost:8183/chunk-3LFKNP7Q.js:47192:10)
    at _ServoyBootstrapCalendar.initializePicker
(http://localhost:8183/chunk-3LFKNP7Q.js:48013:21)
    at _ServoyBootstrapCalendar.svyOnChanges
(http://localhost:8183/chunk-3LFKNP7Q.js:47981:14)
    at _ServoyBootstrapCalendar.ngOnChanges
(http://localhost:8183/chunk-3LFKNP7Q.js:9652:14)